CREATE TABLE Human
(
Id INTEGER PRIMARY KEY,
Name TEXT,
Age INTEGER DEFAULT 18 CHECK(Age >0 AND Age < 100),
Rights BOOLEAN NOT NULL
CarId INTEGER REFERENCES Cars(Id)
);

CREATE TABLE Cars
(
Id INTEGER PRIMARY KEY,
Brand TEXT,
Model TEXT,
Price MONEY
);